### ISSUE TITLE
Traceback in extractWithoutOrder

### ISSUE THREAD

**Issue by LearnLinuxTV** [forslund/mpd_skill#15]
I am seeing the following issue when I try to use this skill on a Mark 1:

```019-12-23 16:46:49.050 | INFO     |   855 | mpd_skill_forslund:handle_play_playlist:126 | Handling play request
2019-12-23 16:46:49.065 | ERROR    |   855 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:798 | An error occurred while processing a request in MPD Skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 92, in extractWithoutOrder
    return StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mpd_skill.forslund/__init__.py", line 128, in handle_play_playlist
    self.playlist)
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/fuzzywuzzy/process.py", line 230, in extractOne
    return max(best_list, key=lambda i: i[1])
RuntimeError: generator raised StopIteration```

**Comment by ProjectMoon** [comment]
This is also happening on a Raspberry Pi. It seems to be that the `self.playlist` variable is empty. Perhaps because the `_connect` method is not running properly?

**Comment by forslund** [comment]
You are probably correct, this skill hasn't been updated with to conform with the latest changes in Mycroft, it uses the old `.config` member to get the server config. It should be updated with a settingsmeta file and use the .settings and should really switch over to the common play framework. I have a wip thing here I can push if you're interested in testing.

**Comment by forslund** [comment]
Pushed the branch [cps-update](https://github.com/forslund/mpd_skill/tree/cps-update). This switches over to using skill settings. and can be configured from https://home.mycroft.ai. It also uses the common play framework so it'll play nicer with other playback skills.

**Comment by LearnLinuxTV** [comment]
That branch seems to solve the issue.

**Comment by forslund** [comment]
Excellent to hear. I'll look it over and merge it into master...Should create a couple of test cases and submit the skill to the marketplace...
